#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'build-essential'
cookbook 'apt'
cookbook 'git'
cookbook 'nginx'
cookbook 'memcached'
cookbook 'postgresql'
cookbook 'python'
cookbook 'gunicorn'
cookbook 'database'
